version: 0.2
env:
  secrets-manager:
    SONAR_USER: "SonarQubeUserSecretNew-wL3Hp9jD2h96:username"
    SONAR_PASSWORD: "SonarQubeUserSecretNew-wL3Hp9jD2h96:password"
    SONAR_ACCESS_TOKEN: "SonarQubeUserSecretNew-wL3Hp9jD2h96:access_token"
  variables:
    CHANGELIST: "-SNAPSHOT"
    AWS_ACCOUNT_ID: "518241560725"
    SONAR_HOST: "http://54.229.164.107:9000"
    SONAR_PROJECT_KEY: "nuxeo-core"


phases:

  install:
    runtime-versions:
      java: corretto11
    commands:
      - aws s3 sync s3://db-dev-buildartifacts/tools/ tools/
      - chmod a+x -R tools/
      - . ./tools/prepEnv-new.sh
      - echo Build Started


  build:
    commands:
      - VERSION=$(printf '%(%Y.%m.%d)T\n' -1)
      - if [ "$CODEBUILD_GIT_BRANCH" == "development" ];
        then
        CHANGELIST=-$CODEBUILD_BUILD_NUMBER;
        fi
      - MAVEN_ARGS="-Dchangelist=$CHANGELIST -Drevision=$VERSION -DskipTests -T4C -nsu -ntp -Dnuxeo.skip.enforcer=true"
      - echo Build started on `date`
      - mvn clean compile install deploy $MAVEN_ARGS
      - echo Deployment done `date`
