<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.nuxeo</groupId>
    <artifactId>nuxeo-parent</artifactId>
    <version>2023.20</version>
  </parent>

  <groupId>org.nuxeo.retention</groupId>
  <artifactId>nuxeo-retention-parent</artifactId>
  <name>Nuxeo Retention Management Parent</name>
  <version>2023.5.13</version>
  <packaging>pom</packaging>
  <description>The Nuxeo Retention Management addon adds the capability to create and attach retention rules to documents
    in order to perform advanced record management.
  </description>

  <properties>
    <frontend-plugin.node.version>v22.17.0</frontend-plugin.node.version>
    <frontend-plugin.node.download.root/>
    <frontend-plugin.node.server.id/>
    <frontend-plugin.node.npm.userconfig>${env.HOME}/.npmrc</frontend-plugin.node.npm.userconfig>
    <frontend-plugin.ftest.nuxeoUrl>http://localhost:8080</frontend-plugin.ftest.nuxeoUrl>
  </properties>

  <modules>
    <module>nuxeo-retention</module>
    <module>nuxeo-retention-package</module>
    <module>nuxeo-retention-web</module>
  </modules>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.nuxeo.retention</groupId>
        <artifactId>nuxeo-retention</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.nuxeo.retention</groupId>
        <artifactId>nuxeo-retention-package</artifactId>
        <version>${project.version}</version>
        <type>zip</type>
      </dependency>
      <dependency>
        <groupId>org.nuxeo.retention</groupId>
        <artifactId>nuxeo-retention-web</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <repositories>
    <repository>
      <id>public</id>
      <url>https://packages.nuxeo.com/repository/maven-public</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <updatePolicy>always</updatePolicy>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>public</id>
      <url>https://packages.nuxeo.com/repository/maven-public</url>
      <name>Nuxeo</name>
      <releases>
        <enabled>true</enabled>
      </releases>
      <!-- no need to enable snapshots for plugin repository -->
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>com.github.eirslett</groupId>
          <artifactId>frontend-maven-plugin</artifactId>
          <version>1.15.1</version>
          <configuration>
            <nodeVersion>${frontend-plugin.node.version}</nodeVersion>
            <nodeDownloadRoot>${frontend-plugin.node.download.root}</nodeDownloadRoot>
            <serverId>${frontend-plugin.node.server.id}</serverId>
            <environmentVariables>
              <NPM_CONFIG_USERCONFIG>${frontend-plugin.node.npm.userconfig}</NPM_CONFIG_USERCONFIG>
            </environmentVariables>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

  <scm>
    <connection>scm:git:git://github.com/nuxeo/nuxeo-retention.git</connection>
    <developerConnection>scm:git:ssh://git@github.com:nuxeo/nuxeo-retention.git</developerConnection>
    <url>https://github.com/nuxeo/nuxeo-retention</url>
  </scm>

</project>
