
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    # add tls configuration
    domain: napps.dev.nuxeo.com
    exposer: Ingress
    http: true
    tlsacme: true
    tlsSecretName: napps-tls
    urltemplate: '"{{.Service}}-{{.Namespace}}.{{.Domain}}"'

cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

nuxeo:
  fullnameOverride: preview
  nuxeo:
    podLabels:
      branch: "master"
      team: napps
      resource: pod
      usage: preview
    service:
      annotations:
        fabric8.io/expose: "true"
        fabric8.io/ingress.annotations: |-
          nginx.ingress.kubernetes.io/proxy-body-size: 0
          nginx.ingress.kubernetes.io/server-snippet: ignore_invalid_headers off;
      labels:
        branch: "master"
        team: napps
        resource: service
        usage: preview
    image:
      repository: 10.63.243.100:5000/nuxeo/nuxeo-retention
      tag: 11.0.0-rc.30
      pullPolicy: Always
    persistence:
      enabled: disable
    packages: nuxeo-web-ui /packages/nuxeo-retention-package-*.zip
    livenessProbe:
      initialDelaySeconds: 420
      periodSeconds: 20
      successThreshold: 1
      failureThreshold: 5
      timeoutSeconds: 10
    readinessProbe:
        periodSeconds: 20
        initialDelaySeconds: 420
        successThreshold: 1
        timeoutSeconds: 10
        failureThreshold: 5
    customParams: |-
      org.nuxeo.connect.url=https://nos-preprod-connect.nuxeocloud.com/nuxeo/site/
    customEnvs:
      - name: NUXEO_CLID
        valueFrom:
          secretKeyRef:
            name: instance-clid-preprod
            key: CLID
    tolerations:
    - key: team
      operator: Equal
      value: napps
      effect: NoSchedule
    nodeSelector:
      team: napps
  mongodb:
    deploy: true
    labels:
      branch: master
      resource: deployment
      team: napps
      usage: preview
    podLabels:
      branch: master
      resource: pod
      team: napps
      usage: preview
    tolerations:
      - key: team
        operator: Equal
        value: napps
        effect: NoSchedule
    nodeSelector:
      team: napps
    resources:
      requests:
        cpu: 500m
        memory: 250Mi
      limits:
        cpu: 1
        memory: 500Mi
tags:
  mongodb: true
