
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    # add tls configuration
    domain: napps.dev.nuxeo.com
    exposer: Ingress
    http: true
    tlsacme: true
    tlsSecretName: napps-tls
    urltemplate: '"{{.Service}}-{{.Namespace}}.{{.Domain}}"'
  Image: "ghcr.io/jenkins-x/exposecontroller"
  ImageTag: "2.3.118"

cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

nuxeo:
  fullnameOverride: preview
  nuxeo:
    podLabels:
      branch: "lts-2021"
      team: napps
      resource: pod
      usage: preview
    service:
      annotations:
        fabric8.io/expose: "true"
        fabric8.io/ingress.annotations: |-
          nginx.ingress.kubernetes.io/proxy-body-size: 0
          nginx.ingress.kubernetes.io/server-snippet: ignore_invalid_headers off;
      labels:
        branch: "lts-2021"
        team: napps
        resource: service
        usage: preview
    image:
      repository: docker-registry.napps.dev.nuxeo.com/nuxeo/nuxeo-retention
      tag: 2021.2.2-rc.0
      pullPolicy: Always
    persistence:
      enabled: disable
    packages: nuxeo-web-ui
    livenessProbe:
      initialDelaySeconds: 420
      periodSeconds: 20
      successThreshold: 1
      failureThreshold: 5
      timeoutSeconds: 10
    readinessProbe:
        periodSeconds: 20
        initialDelaySeconds: 420
        successThreshold: 1
        timeoutSeconds: 10
        failureThreshold: 5
    customEnvs:
      - name: NUXEO_CLID
        valueFrom:
          secretKeyRef:
            name: instance-clid
            key: CLID
    tolerations:
    - key: team
      operator: Equal
      value: napps
      effect: NoSchedule
    nodeSelector:
      team: napps
  mongodb:
    deploy: true
    labels:
      branch: lts-2021
      resource: deployment
      team: napps
      usage: preview
    podLabels:
      branch: lts-2021
      resource: pod
      team: napps
      usage: preview
    tolerations:
      - key: team
        operator: Equal
        value: napps
        effect: NoSchedule
    nodeSelector:
      team: napps
    resources:
      requests:
        cpu: 500m
        memory: 250Mi
      limits:
        cpu: 1
        memory: 500Mi
tags:
  mongodb: true
