# Workflow that syncronizes translations from Crowdin
name: Crowdin

on:
  # Make workflow reusable, to be called by the scheduled crowdin workflow in the default branch
  workflow_call:

  # Sync when a commit is done on the reference branches
  push:
    branches: ["lts-2025"]
    paths:
      - 'nuxeo-retention-web/i18n/messages.json'

jobs:
  crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: lts-2025

      - name: Crowdin Action
        id: crowdin-sync
        uses: crowdin/github-action@v2.15.2
        with:
          # Disable 'git checkout "${GITHUB_REF#refs/heads/}"'
          skip_ref_checkout: true

          # Tokens
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

          # Load external configuration file (to support translation rename)
          config: crowdin-conf.yml

          # Upload sources for translation
          upload_sources: true

          # Auto-approve reference sentences we are pushing (english)
          auto_approve_imported: true

          # Name of the branch where to merge the translations
          localization_branch_name: crowdin-translations-update-lts-2025
          pull_request_base_branch_name: lts-2025
          create_pull_request: true
          pull_request_reviewers: 'manonlumeau'
          pull_request_title: New Crowdin translations by GitHub Action (lts-2025)

          # Automatically download all the new translations
          download_translations: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for the PR
        if: steps.crowdin-sync.outputs.pull_request_url
        run: gh pr --repo $GITHUB_REPOSITORY merge ${{ steps.crowdin-sync.outputs.pull_request_url }} --auto --rebase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
